// <auto-generated />
using System;
using McpTrackTokens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McpTrackTokens.Infrastructure.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260717093431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ActivityWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EditorSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InactivityThresholdMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EditorSessionId");

                    b.HasIndex("EndedAtUtc");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ProjectId", "StartedAtUtc", "EndedAtUtc");

                    b.ToTable("ActivityWindows", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.CostAllocationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Priority");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CostAllocationRules", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.EditorSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EditorVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB")
                        .HasDefaultValue(new byte[0]);

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndedAtUtc");

                    b.HasIndex("ExternalSessionId");

                    b.HasIndex("LastActivityAtUtc");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RepositoryPath");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("Editor", "ExternalSessionId");

                    b.ToTable("EditorSessions", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ExternalUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRecordId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PeriodEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PeriodStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ReportedCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIdentifier")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ExternalRecordId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("ImportedAtUtc");

                    b.HasIndex("Source");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("Source", "ExternalRecordId")
                        .IsUnique()
                        .HasFilter("\"ExternalRecordId\" IS NOT NULL");

                    b.ToTable("ExternalUsageRecords", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasFilter("\"FileHash\" IS NOT NULL");

                    b.HasIndex("Source");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryRemoteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryRepositoryPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB")
                        .HasDefaultValue(new byte[0]);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientName");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("PrimaryRemoteUrl");

                    b.HasIndex("PrimaryRepositoryPath");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ProjectAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NormalizedAlias");

                    b.HasIndex("ProjectId");

                    b.HasIndex("NormalizedAlias", "AliasType")
                        .IsUnique();

                    b.ToTable("ProjectAliases", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ProjectRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedRemoteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NormalizedPath");

                    b.HasIndex("NormalizedRemoteUrl");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "NormalizedPath")
                        .IsUnique();

                    b.ToTable("ProjectRepositories", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.PromptActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributionConfidence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributionMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Editor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EditorSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalConversationId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRequestId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptContentEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PromptContentStored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResponseCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EditorSessionId");

                    b.HasIndex("ExternalConversationId");

                    b.HasIndex("ExternalEventId");

                    b.HasIndex("ExternalRequestId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RepositoryPath");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("Editor", "ExternalEventId")
                        .IsUnique()
                        .HasFilter("\"ExternalEventId\" IS NOT NULL");

                    b.ToTable("PromptActivityEvents", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.TrackingApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedEditors")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedMachineNames")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("LastUsedAtUtc");

                    b.ToTable("TrackingApiKeys", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.UsageAttribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivityEventId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocatedCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("AllocatedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllocatedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllocatedTotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocationPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributionMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EditorSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExternalUsageRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityEventId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EditorSessionId");

                    b.HasIndex("ExternalUsageRecordId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewedAtUtc");

                    b.ToTable("UsageAttributions", (string)null);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ActivityWindow", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.EditorSession", null)
                        .WithMany()
                        .HasForeignKey("EditorSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("McpTrackTokens.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.EditorSession", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ExternalUsageRecord", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ProjectAlias", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.ProjectRepository", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.PromptActivityEvent", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.EditorSession", null)
                        .WithMany()
                        .HasForeignKey("EditorSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("McpTrackTokens.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("McpTrackTokens.Domain.Entities.UsageAttribution", b =>
                {
                    b.HasOne("McpTrackTokens.Domain.Entities.PromptActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("McpTrackTokens.Domain.Entities.EditorSession", null)
                        .WithMany()
                        .HasForeignKey("EditorSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("McpTrackTokens.Domain.Entities.ExternalUsageRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalUsageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McpTrackTokens.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
